name: fast_api
channels:
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17.3=py310haa95532_0
  - annotated-types=0.6.0=py310haa95532_0
  - anyio=4.2.0=py310haa95532_0
  - beautifulsoup4=4.12.3=py310haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli-python=1.0.9=py310hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.7.14=h4c7d964_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - fastapi=0.103.0=py310haa95532_0
  - h11=0.14.0=py310haa95532_0
  - idna=3.7=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=pyhd8ed1ab_0
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.16=h2bbff1b_3
  - libxml2=2.13.8=h866ff63_0
  - libxslt=1.1.41=h0739af5_0
  - lxml=5.3.0=py310h395c83e_1
  - markupsafe=2.1.5=py310h8d17308_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - numexpr=2.10.1=py310h4cd664f_0
  - numpy=2.2.5=py310h5f75535_0
  - numpy-base=2.2.5=py310h23d94f8_0
  - openssl=3.5.1=h725018a_0
  - packaging=24.2=py310haa95532_0
  - pandas=2.2.3=py310h5da7b33_0
  - pefile=2023.2.7=py310haa95532_0
  - pip=24.0=py310haa95532_0
  - pydantic=2.5.3=py310haa95532_0
  - pydantic-core=2.14.6=py310h062c2fa_0
  - pyinstaller=6.12.0=py310h0416ee5_0
  - pyinstaller-hooks-contrib=2025.1=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.14=he1021f5_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=py310haa95532_0
  - pywin32-ctypes=0.2.2=py310haa95532_0
  - requests=2.32.3=py310haa95532_1
  - setuptools=69.5.1=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sniffio=1.3.0=py310haa95532_0
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - starlette=0.27.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - typing-extensions=4.11.0=py310haa95532_0
  - typing_extensions=4.11.0=py310haa95532_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.2.3=py310haa95532_0
  - uvicorn=0.20.0=py310haa95532_0
  - vc=14.3=h2b53caa_30
  - vc14_runtime=14.44.35208=h818238b_30
  - vs2015_runtime=14.44.35208=h38c0c73_30
  - wheel=0.43.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
prefix: C:\Users\anton\.conda\envs\fast_api
