[workspace]
authors = ["Anton Hardock <antonhardock@web.de>"]
channels = ["conda-forge"]
name = "timely"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10.14"
fastapi = "==0.103"
python-multipart = "==0.0.20"
pydantic = "==2.5.3"
uvicorn = "==0.20.0"
jinja2 = "==3.1.4"
lxml = "==5.3.0"
pyinstaller = "==6.17.0"
